# Generated by Django 5.1.2 on 2024-11-04 09:01

import django.core.validators
import osauhingud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osauhingud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osauhing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(3)])),
                ('registrycode', models.IntegerField(validators=[osauhingud.models.validate_seven_digits])),
                ('foundingdate', models.DateField(auto_now_add=True)),
                ('totalcapital', models.IntegerField(validators=[django.core.validators.MinValueValidator(2500)])),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
