# Generated by Django 5.1.2 on 2024-11-04 14:13

import django.core.validators
import django.db.models.deletion
import osauhingud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osauhingud', '0002_osauhing_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osauhing',
            name='registrycode',
            field=models.PositiveIntegerField(validators=[osauhingud.models.validate_seven_digits]),
        ),
        migrations.AlterField(
            model_name='osauhing',
            name='totalcapital',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2500)]),
        ),
        migrations.CreateModel(
            name='IndividualShareHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('personal_id_code', models.PositiveIntegerField(unique=True)),
                ('shareholder_share', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_shareholders', to='osauhingud.osauhing')),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntityShareHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('shareholder_share', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_shareholders', to='osauhingud.osauhing')),
            ],
        ),
    ]
