# Generated by Django 5.1.2 on 2024-11-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osauhingud', '0003_alter_osauhing_registrycode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_shareholders', to='osauhingud.osauhing')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='osauhing',
            name='shareholders',
            field=models.ManyToManyField(blank=True, related_name='companies', to='osauhingud.shareholder'),
        ),
    ]
