# Generated by Django 5.1.2 on 2024-11-04 16:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osauhingud', '0004_shareholder_osauhing_shareholders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='company',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='object_id',
        ),
        migrations.AddField(
            model_name='legalentityshareholder',
            name='company_registry_code',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osauhingud.individualshareholder'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osauhingud.legalentityshareholder'),
        ),
    ]
