# Generated by Django 5.1.2 on 2024-11-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osauhingud', '0005_remove_shareholder_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualshareholder',
            name='company',
        ),
        migrations.RemoveField(
            model_name='legalentityshareholder',
            name='company',
        ),
    ]
