# Generated by Django 5.1.2 on 2024-11-05 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osauhingud', '0007_individualshareholder_company_registry_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualshareholder',
            name='company_registry_code',
        ),
        migrations.RemoveField(
            model_name='legalentityshareholder',
            name='company_registry_code',
        ),
        migrations.AddField(
            model_name='legalentityshareholder',
            name='registry_code',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
