# Generated by Django 5.1.2 on 2024-11-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osauhingud', '0008_remove_individualshareholder_company_registry_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osauhing',
            name='foundingdate',
            field=models.DateField(),
        ),
    ]
